### PR TITLE
Get all students and all universities 

### PR DESCRIPTION
**Pull request by Penelope32**

### CODE REVIEW

**Comment by ndzalamabasa** [comment]
Good job @Penelope32 , however, the layout is not responsive. are planning to make it responsive at a later stage or finding it difficult to make it responsive?

**Comment by Penelope32** [comment]
I will fix it

**Comment by ndzalamabasa** [comment]
> I will fix it

At a later stage or now?

**Comment by Penelope32** [comment]
Currently, I'm focusing on integrating the necessary functionality and ensuring that all features are working as expected. once I am done, I'll prioritize addressing the responsiveness of the page. I should do it once Vuyo pushes his structure to main

**Review by ndzalamabasa — APPROVED** [review]

**Pull request merged**
